DROP TABLE E1;
DROP TABLE E2;
DROP TABLE E3;

CREATE TABLE E1 (
	K1 char(1) NOT NULL PRIMARY KEY,
	A INT NOT NULL);

CREATE TABLE E2 (
	K2 CHAR(1) NOT NULL PRIMARY KEY,
	B INT NOT NULL,
	E1R1 CHAR(1) NOT NULL REFERENCES E1(K1));

CREATE TABLE E3 (
	K3 CHAR(1) NOT NULL PRIMARY KEY,
	C INT NOT NULL,
	E2R2 CHAR(1) NOT NULL REFERENCES E2(K2));

CREATE OR REPLACE TRIGGER PreventAGreaterThanC
BEFORE INSERT ON E3
REFERENCING NEW AS N
FOR EACH ROW
WHEN (EXISTS (SELECT *
			  FROM E1, E2
			  WHERE N.E2R2 = E2.K2 AND E2.E1R1 = E1.K1 AND E1.A > N.C))
SIGNAL SQLSTATE '70000' ('Il valore di C deve essere maggiore di quello di A della stessa tupla che referenzia');


INSERT INTO E1 (K1, A) VALUES ('A', 10);
INSERT INTO E1 (K1, A) VALUES ('B', 20);
INSERT INTO E1 (K1, A) VALUES ('C', 30);

INSERT INTO E2 (K2, B, E1R1) VALUES ('X', 100, 'A');
INSERT INTO E2 (K2, B, E1R1) VALUES ('Y', 200, 'B');
INSERT INTO E2 (K2, B, E1R1) VALUES ('Z', 300, 'C');

INSERT INTO E3 (K3, C, E2R2) VALUES ('P', 15, 'X');
INSERT INTO E3 (K3, C, E2R2) VALUES ('Q', 25, 'Y');
INSERT INTO E3 (K3, C, E2R2) VALUES ('R', 35, 'Z');

INSERT INTO E3 (K3, C, E2R2) VALUES ('S', 10, 'Y'); -- ERRORE